var class_m_pewsey_1_1_mania_map_1_1_exceptions_1_1_collectable_spot_not_found_exception =
[
    [ "CollectableSpotNotFoundException", "class_m_pewsey_1_1_mania_map_1_1_exceptions_1_1_collectable_spot_not_found_exception.html#ac88fcbddbb25e2480a5df4dc53b94bbe", null ]
];